const CHANGE_TAB = 'header/CHANEG_TAB';
const FILTER_DATA = 'header/FILTER_DATA';
const CHANGE_FILTER = 'header/CHANGE_FILTER';
const CONTENTLIST_DATA = 'contentList/CONTENTLIST_DATA';

export default { CHANGE_TAB, FILTER_DATA, CHANGE_FILTER, CONTENTLIST_DATA };
